### ISSUE TITLE
gtfparse call

### ISSUE THREAD

**Issue by rpm78** [ed-lau/jcast#3]
while running jcast the following error was produced
```
Traceback (most recent call last):
  File "psq.py", line 456, in <module>
    args.func(args)
  File "psq.py", line 116, in psqM
    gtf.read_gtf()
  File "/home/rpm/jcast/get_jxn.py", line 32, in read_gtf
    self.annot = gtp.read_gtf_as_dataframe(self.path)
AttributeError: module 'gtfparse' has no attribute 'read_gtf_as_dataframe'
```
this can be suppressed by changing ``` read_gtf_as_dataframe``` to ```read_gtf``` in line 32 of get_jxn.py.

**Comment by ed-lau** [comment]
Thanks! fixed.
