### ISSUE TITLE
sorting by transcript support level with non-mouse non-human species

### ISSUE THREAD

**Issue by rpm78** [ed-lau/jcast#4]
while running jcast with a rat gtf file the following error was produced 
```
Processing MXE Junctions:   0%|                                                                                                                                                                                      | 0/4816 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "psq.py", line 456, in <module>
    args.func(args)
  File "psq.py", line 229, in psqM
    junction.get_translated_region(gtf)
  File "/home/rpm/jcast/get_jxn.py", line 99, in get_translated_region
    gtf0_start = gtf0.query('feature == "start_codon"').sort_values(['transcript_support_level']).sort_values(['ccds_id']).loc[:, 'start']
  File "/home/rpm/miniconda2/envs/py36/lib/python3.6/site-packages/pandas/core/frame.py", line 4927, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/home/rpm/miniconda2/envs/py36/lib/python3.6/site-packages/pandas/core/generic.py", line 1692, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'transcript_support_level'
```
I think that transcript support level is only flagged in human and mouse, so that this will be a problem for other species.  Depending on which species you may (or may not!) want to support, APPRIS tags might be an option. (http://appris.bioinfo.cnio.es/#/)

**Comment by ed-lau** [comment]
I will look into APPRIS. For now will include option to bypass the sorting.

**Comment by ed-lau** [comment]
jcast will now bypass transcript support level/ccds_id sorting if the keys do not exist. will look into a more general strategy to trim untranslated regions in the long term.
